### ISSUE TITLE
Required StochJuMP

### ISSUE THREAD

**Issue by adowling2** [Argonne-National-Laboratory/DSPsolver.jl#3]
I'm getting the following error:

`julia> Pkg.clone("https://github.com/Argonne-National-Laboratory/DSPsolver.jl")
INFO: Cloning DSPsolver from https://github.com/Argonne-National-Laboratory/DSPsolver.jl
INFO: Computing changes...
ERROR: unknown package StochJuMP required by DSPsolver
 in error at ./error.jl:21
 in requirements at ./pkg/query.jl:11
 in resolve at ./pkg/entry.jl:404
 in clone at pkg/entry.jl:170
 in clone at pkg/entry.jl:186
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in clone at pkg.jl:34`

Adding the package StochJuMP clears up the issue:
`Pkg.clone("https://github.com/kibaekkim/StochJuMP.jl")`

The documentation says DSPsolver.jl needs StructJuMP.

**Comment by kibaekkim** [comment]
Thanks for reporting this.

We recently replaced the StochJuMP package by the StructJuMP package. But, there were some StochJuMP codes in the codes. We removed them.
